agent:
  # -- Mode to run Grafana Agent in. Can be "flow" or "static".
  mode: 'flow'
  configMap:
    # -- Create a new ConfigMap for the config file.
    create: true
    # -- Content to assign to the new ConfigMap.  This is passed into `tpl` allowing for templating from values.
    content: |
      logging {
        level = "debug"
        format = "logfmt"
      }

      discovery.kubernetes "pyroscope_kubernetes" {
        role = "pod"
      }

      pyroscope.write "example" {
        // Send metrics to a locally running Pyroscope instance.
        endpoint {
          url = "http://pyroscope.pyroscope-test.svc.cluster.local.:4040"
        }
        external_labels = {
          "env" = "example",
        }
      }

      pyroscope.scrape "default" {
        targets = discovery.kubernetes.pyroscope_kubernetes.targets
        forward_to = [pyroscope.write.example.receiver]
      }